name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - uses: actions/checkout@master
      - name: checkout
        id: checkout

        # Put your action repo here
        uses: kracekumar/type_coverage_as_comment@master

      - name: Generate coverage
        run: |
          pip install mypy lxml
          mypy . --html-report "mypy_report"

      - name: upload type coverage file
        uses: actions/upload-artifact@v2
        with:
          name: mypy_report
          path: mypy_report

  Run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: mkdir -p /home/runner/work/type_coverage_as_comment/type_coverage_as_comment/
      - name: Download the type coverage file
        id: download
        uses: actions/download-artifact@v2
        with:
          name: mypy_report
          path: /home/runner/work/type_coverage_as_comment/type_coverage_as_comment/mypy_report

      - name: set env variable
        run: echo "HTML_REPORT=/home/runner/work/type_coverage_as_comment/type_coverage_as_comment/mypy_report" >> $GITHUB_ENV

      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: kracekumar/type_coverage_as_comment@master
