name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: kracekumar/type_coverage_as_comment@master
        with:
          html_report: "mypy_report/index.html"
      - name: Check outputs
        run: |
          pip install mypy
          mypy . --html-report "mypy_report"
          test "${{ steps.selftest.outputs.myOutput }}"
