name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - uses: actions/checkout@master
      - name: checkout
        id: checkout

        # Put your action repo here
        uses: kracekumar/type_coverage_as_comment@master

      - name: Generate coverage
        run: |
          pip install mypy lxml
          mypy . --html-report "mypy_report"

      - name: upload type coverage file
        uses: actions/upload-artifact@v2
        with:
          name: mypy_report
          path: mypy_report

  Run:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      modified_files: ${{ steps.diff.outputs.modified_files }}

    steps:
      - name: Download the type coverage file
        id: download
        uses: actions/download-artifact@v2
        with:
          name: mypy_report

      - name: Checkout
        id: checkout_repo
        uses: actions/checkout@master

      - name: Run git diff
        id: diff
        run: |
          echo "$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
          echo "::set-output name=modified_files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"

      - name: Self test
        id: selftest
        uses: kracekumar/type_coverage_as_comment@master
        env:
          HTML_REPORT: ${{steps.download.outputs.download-path}}

      - name: Check outputs and modified files
        run: |
          echo "RUN_ID: ${{ steps.selftest.outputs.GITHUB_RUN_ID }}"
          echo ${{steps.diff.outputs.modified_files}}
