name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: kracekumar/type_coverage_as_comment@master
        with:
          html_report: "mypy_report/index.html"
      - name: Check outputs
        run: |
          pip install mypy lxml
          mypy . --html-report "mypy_report"
          test "${{ steps.selftest.outputs.myOutput }}"
