name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: set env variable
        run: echo "HTML_REPORT=mypy_report/index.html" >> $GITHUB_ENV

      - uses: actions/checkout@master
      - name: checkout
        id: checkout

        # Put your action repo here
        uses: kracekumar/type_coverage_as_comment@master

      - name: Generate coverage
        run: |
          pip install mypy lxml
          mypy . --html-report "mypy_report"

      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: kracekumar/type_coverage_as_comment@master
